[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "fontconfig"
]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/server.js"
