[phases.setup]
nixPkgs = [
  "nodejs_20",
  "glib",
  "nss",
  "nspr",
  "dbus",
  "atk",
  "cups",
  "libdrm",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libxcb",
  "xorg.libXScrnSaver",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXtst",
  "libxkbcommon",
  "freetype",
  "harfbuzz",
  "fontconfig",
  "cairo",
  "pango",
  "alsa-lib",
  "expat",
  "mesa",
  "at-spi2-atk",
  "at-spi2-core",
  "gtk3",
  "gdk-pixbuf"
]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/server.js"
