[phases.setup]
nixPkgs = [
  "nodejs_20",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "wget",
  "fontconfig",
  "expat",
  "libdrm",
  "mesa",
  "libxkbcommon",
  "at-spi2-atk",
  "cups",
  "dbus",
  "libxrandr",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libxcb",
  "xorg.libXScrnSaver"
]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/server.js"
